[package]
name = "egor"
version = "0.10.0"
edition = "2024"
description = "A dead simple 2D graphics engine"
repository = "https://github.com/wick3dr0se/egor"
license = "MIT"
keywords = ["2d", "graphics", "wgpu", "winit"]
categories = ["game-development", "graphics"]
exclude = ["media/"]

[workspace]
resolver = "3"
members = ["crates/*", "demos/*", "xtask"]

[dependencies]
egor_app = { path = "crates/egor_app", version = "0.10.0" }
egor_glue = { path = "crates/egor_glue", version = "0.10.0" }
egor_render = { path = "crates/egor_render", version = "0.10.0" }

[features]
default = []
log = ["egor_app/log"]

angle = ["egor_render/angle"]
gles = ["egor_render/gles"]
vulkan = ["egor_render/vulkan"]
webgl = ["egor_render/webgl"]

hot_reload = ["egor_glue/hot_reload"]
ui = ["egor_glue/ui"]

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
strip = false
lto = false
panic = "unwind"
codegen-units = 16
