[package]
name = "egor_render"
version = "0.10.0"
edition = "2024"
description = "A dead simple 2D wgpu renderer"
repository = "https://github.com/wick3dr0se/egor"
license = "MIT"
keywords = ["egor", "wgpu"]

[dependencies]
bytemuck = "1.23.0"
image = { version = "0.25.6", default-features = false, features = ["png"] }

[dev-dependencies]
pollster = "0.4.0"
winit = "0.30.12"

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
wgpu = {
  version = "29.0.1",
  default-features = false,
  features = [
    "vulkan",
    "wgsl",
  ]
}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = {
  version = "29.0.1",
  default-features = false,
  features = [
    "webgpu",
    "wgsl",
  ]
}

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = {
  version = "29.0.1",
  default-features = false,
  features = [
    "metal",
    "wgsl",
  ]
}

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = {
  version = "29.0.1",
  default-features = false,
  features = [
    "dx12",
    "wgsl",
  ]
}

[features]
default = []
angle = ["wgpu/angle"]
gles = ["wgpu/gles"]
vulkan = ["wgpu/vulkan"]
webgl = ["wgpu/webgl"]
